// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIUSFtmqyD4xLG-yInVFKraYFiCIVXgQ',
    appId: '1:140410400136:web:c113da348491650dbd5e3d',
    messagingSenderId: '140410400136',
    projectId: 'groupstudyplanner-96c44',
    authDomain: 'groupstudyplanner-96c44.firebaseapp.com',
    databaseURL: 'https://groupstudyplanner-96c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupstudyplanner-96c44.appspot.com',
    measurementId: 'G-EJ23GH0CDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxj8QBdSqO2Yi346zxpDLSlfhOU5h2N4E',
    appId: '1:140410400136:android:8cb32ea62f84facebd5e3d',
    messagingSenderId: '140410400136',
    projectId: 'groupstudyplanner-96c44',
    databaseURL: 'https://groupstudyplanner-96c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupstudyplanner-96c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlm2tErfUmDQjlg-L3WYlIokYTDFMh-pg',
    appId: '1:140410400136:ios:869690fbe49757b4bd5e3d',
    messagingSenderId: '140410400136',
    projectId: 'groupstudyplanner-96c44',
    databaseURL: 'https://groupstudyplanner-96c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupstudyplanner-96c44.appspot.com',
    iosClientId: '140410400136-kooril743qp37j75r1bis9fkk8cofon9.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymatcherf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlm2tErfUmDQjlg-L3WYlIokYTDFMh-pg',
    appId: '1:140410400136:ios:e2eac0b44684c2c4bd5e3d',
    messagingSenderId: '140410400136',
    projectId: 'groupstudyplanner-96c44',
    databaseURL: 'https://groupstudyplanner-96c44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'groupstudyplanner-96c44.appspot.com',
    iosClientId: '140410400136-3pjn5tt6s9pfbh5774u47b1ofuoidn8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymatcherf.RunnerTests',
  );
}
